Adding endpoint event ontologies
threatgrid/ctim pull request #387
Opened 2022-11-30 08:16 UTC by jyoverma

- Added process_id to observable type vocabulary
- Added event ontologies
- Added context to Sighting schema
- Added Sighting examples for new event types

2023-02-24 23:35 UTC, rplevy requested changes

2023-02-24 23:35 UTC, rplevy commented on src/ctim/examples/sightings.cljc
> +  :sensor "endpoint")
```suggestion
(def sighting-process-create-event
  {:observables [{:value "powershell.exe" :type "process_name"}
                {:value "WmiPrvSE.exe" :type "process_name"}
                {:value "006cef6ef6488721895d93e4cef7fa0709c2692d74bde1e22e2a8719b2a86218" :type "sha256"}]
  :relations [{:relation "Parent_of"
               :source {:type "process_name" :value "WmiPrvSE.exe"}
               :related {:type "process_name" :value "powershell.exe"}}
              {:relation "Launched_By"
               :source {:type "sha256" :value "006cef6ef6488721895d93e4cef7fa0709c2692d74bde1e22e2a8719b2a86218"}
               :related {:type "process_name" :value "powershell.exe"}}]
  :type "sighting"
  :source "Secure Endpoint"
  :title "Process Created Event"
  :context [{:event_type "endpoint.process_start_event"
             :details {:type "ProcessCreateEvent"
                       :creation_time "2022-01-24T17:00:00.000Z"
                       :process_id 10724
                       :process_guid 132465072105597400
                       :process_name "powershell.exe"
                       :process_username "SYSTEM"
                       :process_hash "006cef6ef6488721895d93e4cef7fa0709c2692d74bde1e22e2a8719b2a86218"
                       :process_size 443392
                       :parent_process_id 2236
                       :parent_process_guid 132461352663910600
                       :parent_process_name "WmiPrvSE.exe"
                       :parent_process_username "SYSTEM"
                       :parent_process_hash "385892542cc5a996488262b193061feac4615d66657157c3d4a76251911da334"
                       :parent_process_size 425984}}]
  :external_ids ["secure-endpoint-sighting-b1233f9fc66cb8b27971ffb76d838d5c3d05cbf20b215f9d5dbbd05c4944954b"]
  :targets [{:type "endpoint"
             :observables [{:value "Demo_Dridex" :type "hostname"}]
             :observed_time {:start_time "2022-01-24T17:00:00.000Z"}}]
  :internal true
  :source_uri "https://console.amp.cisco.com/computers/59c5539d-3278-46c9-b5bb-e3e4e0301ae3/trajectory2?_ts=1643044069265&id=6156209764771561503"
  :id "https://private.intel.amp.cisco.com:443/ctia/sighting/sighting-18c7c759-3de5-4579-8427-101ae074d846"
  :schema_version c/ctim-schema-version
  :count 1
  :severity "Medium"
  :tlp "amber"
  :timestamp "2022-01-24T20:07:12.569Z"
  :confidence "High"
  :observed_time {:start_time "2022-01-24T18:52:11.000Z"}
  :sensor "endpoint"})
```

2023-02-24 23:36 UTC, rplevy commented on src/ctim/examples/sightings.cljc
> +  :sensor "endpoint")
This is just a syntax error to fix

2023-03-02 19:10 UTC, msprunck approved these changes

2023-03-02 19:15 UTC, rplevy reviewed
LGTM!

2023-03-02 19:17 UTC, rplevy approved these changes

2023-03-03 19:50 UTC, gbuisson approved these changes

2023-03-03 19:56 UTC, merged